TRADING_DAYS = 252
RISK_FREE_RATE = 0.04  # Placeholder until replaced with a live Treasury source.

USE_COV_SHRINKAGE = True
COV_SHRINKAGE_METHOD = "ledoit_wolf"

USE_BLACK_LITTERMAN = True
BL_RISK_AVERSION = 2.5
BL_TAU = 0.05

TRANSACTION_COST_BPS = 10
SLIPPAGE_BPS = 5

APPLY_TAX_EFFECTS = True
SHORT_TERM_TAX_RATE = 0.35
LONG_TERM_TAX_RATE = 0.15
LONG_TERM_FRACTION = 0.50
DEFAULT_UNREALIZED_GAIN_RATE = 0.20
